BASE_URL = 'https://imagetagger.bit-bots.de'
LOGIN_URL = BASE_URL + '/user/login/?next=/images/'
IMAGE_LINK_URL = BASE_URL + '{image_link}'
IMAGE_LIST_URL = BASE_URL + '/images/imagelist/{imageset_id}'
LOAD_ANNOTATION_URL = BASE_URL + '/annotations/api/annotation/load'
IMAGE_SET_URL = BASE_URL + '/images/imageset/{imageset_id}'

IMAGE_SET_NAME_XPATH = '/html/body/div/div/div/div[2]/div[1]/div/div[2]/table/tbody/tr[1]/td[2]'
IMAGE_SET_TEAM_XPATH = '/html/body/div/div/div/div[2]/div[1]/div/div[2]/table/tbody/tr[2]/td[2]/a'
IMAGE_SET_LOCATION_XPATH = '/html/body/div/div/div/div[2]/div[1]/div/div[2]/table/tbody/tr[3]/td[2]'
IMAGE_SET_DESCRIPTION_XPATH = '/html/body/div/div/div/div[2]/div[1]/div/div[2]/table/tbody/tr[4]/td[2]'
